import type { FindingRow, RiskScoreRow, ScanSessionRow } from "@/lib/store/types";

export function buildSessionMarkdown(input: {
  sessionId: string;
  session: ScanSessionRow;
  findings: FindingRow[];
  riskScores: RiskScoreRow[];
}): string {
  const lines: string[] = [];
  lines.push(`# RepoCheck scan export`);
  lines.push("");
  lines.push(`- **Session ID:** \`${input.sessionId}\``);
  lines.push(`- **Type:** ${input.session.type}`);
  lines.push(`- **Status:** ${input.session.status}`);
  lines.push(`- **Created:** ${input.session.createdAt}`);
  if (input.session.completedAt) {
    lines.push(`- **Completed:** ${input.session.completedAt}`);
  }
  lines.push("");

  const latestRisk = input.riskScores[0];
  if (latestRisk) {
    lines.push(`## Risk score (latest)`);
    lines.push("");
    lines.push(`- **Total:** ${latestRisk.totalScore} / 100`);
    lines.push(`- **Label:** ${latestRisk.label}`);
    lines.push(`- **Confidence:** ${latestRisk.confidence}`);
    lines.push("");
  }

  lines.push(`## Findings (${input.findings.length})`);
  lines.push("");
  for (const f of input.findings) {
    lines.push(`### ${f.severity.toUpperCase()}: ${f.title}`);
    lines.push("");
    if (f.filePath) lines.push(`- **File:** \`${f.filePath}\``);
    if (f.lineHint) lines.push(`- **Hint:** ${f.lineHint}`);
    lines.push(`- **Category:** ${f.category}`);
    lines.push("");
    lines.push(f.description);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push("_Generated by RepoCheck — static heuristics only, not a malware verdict._");
  return lines.join("\n");
}
